/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Drive.v3.Data.GeneratedIds;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Drive.v3.DriveMyNullable;

/**
 * A list of generated file IDs which can be provided in create requests.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Drive API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct GeneratedIds {

  /**
   * The IDs generated for the requesting user in the specified space.
   * The value may be {@code null}.
   */
  @optional public string[] _ids;

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#generatedIds".
   * The value may be {@code null}.
   */
  @optional public string _kind;

  /**
   * The type of file that can be created with these IDs.
   * The value may be {@code null}.
   */
  @optional public string _space;

  /**
   * The IDs generated for the requesting user in the specified space.
   * @return value or {@code null} for none
   */
  public string[] getIds() {
    return _ids;
  }
  /**
   * The IDs generated for the requesting user in the specified space.
   * @param ids ids or {@code null} for none
   */
  public GeneratedIds setIds(string[] _ids) {
    this._ids = _ids;
    return this;
  }

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#generatedIds".
   * @return value or {@code null} for none
   */
  public string getKind() {
    return _kind;
  }
  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#generatedIds".
   * @param kind kind or {@code null} for none
   */
  public GeneratedIds setKind(string _kind) {
    this._kind = _kind;
    return this;
  }

  /**
   * The type of file that can be created with these IDs.
   * @return value or {@code null} for none
   */
  public string getSpace() {
    return _space;
  }
  /**
   * The type of file that can be created with these IDs.
   * @param space space or {@code null} for none
   */
  public GeneratedIds setSpace(string _space) {
    this._space = _space;
    return this;
  }

}