/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Drive.v3.Data.Reply;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Drive.v3.DriveMyNullable;

import Google.Apis.Drive.v3.Data.User;

/**
 * A reply to a comment on a file.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Drive API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct Reply {

  /**
   * The action the reply performed to the parent comment. Valid values are: - resolve  - reopen
   * The value may be {@code null}.
   */
  @optional public string _action;

  /**
   * The author of the reply. The author's email address and permission ID will not be populated.
   * The value may be {@code null}.
   */
  @optional public User _author;

  /**
   * The plain text content of the reply. This field is used for setting the content, while
   * htmlContent should be displayed. This is required on creates if no action is specified.
   * The value may be {@code null}.
   */
  @optional public string _content;

  /**
   * The time at which the reply was created (RFC 3339 date-time).
   * The value may be {@code null}.
   */
  @optional public Nullable!SysTime _createdTime;

  /**
   * Whether the reply has been deleted. A deleted reply has no content.
   * The value may be {@code null}.
   */
  @optional public Nullable!bool _deleted;

  /**
   * The content of the reply with HTML formatting.
   * The value may be {@code null}.
   */
  @optional public string _htmlContent;

  /**
   * The ID of the reply.
   * The value may be {@code null}.
   */
  @optional public string _id;

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#reply".
   * The value may be {@code null}.
   */
  @optional public string _kind;

  /**
   * The last time the reply was modified (RFC 3339 date-time).
   * The value may be {@code null}.
   */
  @optional public Nullable!SysTime _modifiedTime;

  /**
   * The action the reply performed to the parent comment. Valid values are: - resolve  - reopen
   * @return value or {@code null} for none
   */
  public string getAction() {
    return _action;
  }
  /**
   * The action the reply performed to the parent comment. Valid values are: - resolve  - reopen
   * @param action action or {@code null} for none
   */
  public Reply setAction(string _action) {
    this._action = _action;
    return this;
  }

  /**
   * The author of the reply. The author's email address and permission ID will not be populated.
   * @return value or {@code null} for none
   */
  public User getAuthor() {
    return _author;
  }
  /**
   * The author of the reply. The author's email address and permission ID will not be populated.
   * @param author author or {@code null} for none
   */
  public Reply setAuthor(User _author) {
    this._author = _author;
    return this;
  }

  /**
   * The plain text content of the reply. This field is used for setting the content, while
   * htmlContent should be displayed. This is required on creates if no action is specified.
   * @return value or {@code null} for none
   */
  public string getContent() {
    return _content;
  }
  /**
   * The plain text content of the reply. This field is used for setting the content, while
   * htmlContent should be displayed. This is required on creates if no action is specified.
   * @param content content or {@code null} for none
   */
  public Reply setContent(string _content) {
    this._content = _content;
    return this;
  }

  /**
   * The time at which the reply was created (RFC 3339 date-time).
   * @return value or {@code null} for none
   */
  public Nullable!SysTime getCreatedTime() {
    return _createdTime;
  }
  /**
   * The time at which the reply was created (RFC 3339 date-time).
   * @param createdTime createdTime or {@code null} for none
   */
  public Reply setCreatedTime(Nullable!SysTime _createdTime) {
    this._createdTime = _createdTime;
    return this;
  }

  /**
   * Whether the reply has been deleted. A deleted reply has no content.
   * @return value or {@code null} for none
   */
  public Nullable!bool getDeleted() {
    return _deleted;
  }
  /**
   * Whether the reply has been deleted. A deleted reply has no content.
   * @param deleted deleted or {@code null} for none
   */
  public Reply setDeleted(Nullable!bool _deleted) {
    this._deleted = _deleted;
    return this;
  }

  /**
   * The content of the reply with HTML formatting.
   * @return value or {@code null} for none
   */
  public string getHtmlContent() {
    return _htmlContent;
  }
  /**
   * The content of the reply with HTML formatting.
   * @param htmlContent htmlContent or {@code null} for none
   */
  public Reply setHtmlContent(string _htmlContent) {
    this._htmlContent = _htmlContent;
    return this;
  }

  /**
   * The ID of the reply.
   * @return value or {@code null} for none
   */
  public string getId() {
    return _id;
  }
  /**
   * The ID of the reply.
   * @param id id or {@code null} for none
   */
  public Reply setId(string _id) {
    this._id = _id;
    return this;
  }

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#reply".
   * @return value or {@code null} for none
   */
  public string getKind() {
    return _kind;
  }
  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#reply".
   * @param kind kind or {@code null} for none
   */
  public Reply setKind(string _kind) {
    this._kind = _kind;
    return this;
  }

  /**
   * The last time the reply was modified (RFC 3339 date-time).
   * @return value or {@code null} for none
   */
  public Nullable!SysTime getModifiedTime() {
    return _modifiedTime;
  }
  /**
   * The last time the reply was modified (RFC 3339 date-time).
   * @param modifiedTime modifiedTime or {@code null} for none
   */
  public Reply setModifiedTime(Nullable!SysTime _modifiedTime) {
    this._modifiedTime = _modifiedTime;
    return this;
  }

}