/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */
module Google.Apis.Drive.v3.Data.StartPageToken;

import vibe.data.json: optional;
import std.typecons: Nullable;
import std.datetime : SysTime;
import std.conv: to;

import Google.Apis.Drive.v3.DriveMyNullable;

/**
 * Model definition for StartPageToken.
 *
 * This is the D data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Drive API. For a detailed explanation see:
 *
 *
 * @author Robert Aron.
 */
public struct StartPageToken {

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#startPageToken".
   * The value may be {@code null}.
   */
  @optional public string _kind;

  /**
   * The starting page token for listing changes.
   * The value may be {@code null}.
   */
  @optional public string _startPageToken;

  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#startPageToken".
   * @return value or {@code null} for none
   */
  public string getKind() {
    return _kind;
  }
  /**
   * Identifies what kind of resource this is. Value: the fixed string "drive#startPageToken".
   * @param kind kind or {@code null} for none
   */
  public StartPageToken setKind(string _kind) {
    this._kind = _kind;
    return this;
  }

  /**
   * The starting page token for listing changes.
   * @return value or {@code null} for none
   */
  public string getStartPageToken() {
    return _startPageToken;
  }
  /**
   * The starting page token for listing changes.
   * @param startPageToken startPageToken or {@code null} for none
   */
  public StartPageToken setStartPageToken(string _startPageToken) {
    this._startPageToken = _startPageToken;
    return this;
  }

}