/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

module Google.Apis.Drive.v3.DriveScopes;

enum Scopes: int {
  DRIVE,
  DRIVE_APPDATA,
  DRIVE_FILE,
  DRIVE_METADATA,
  DRIVE_METADATA_READONLY,
  DRIVE_PHOTOS_READONLY,
  DRIVE_READONLY,
  DRIVE_SCRIPTS,
};

/**
 * Available OAuth 2.0 scopes for use with the Drive API.
 *
 * @since 1.4
 */
public class DriveScopes {

  /**
   * Returns an unmodifiable set that contains all scopes declared by this class.
   *
   * @since 1.16
   */
  public static string[] all() {
    import std.traits: EnumMembers;
    
    auto noOfScopes = EnumMembers!Scopes.length;
    string[] _scopes = new string[noOfScopes];
    
    _scopes[Scopes.DRIVE] = "https://www.googleapis.com/auth/drive"; 
    _scopes[Scopes.DRIVE_APPDATA] = "https://www.googleapis.com/auth/drive.appdata"; 
    _scopes[Scopes.DRIVE_FILE] = "https://www.googleapis.com/auth/drive.file"; 
    _scopes[Scopes.DRIVE_METADATA] = "https://www.googleapis.com/auth/drive.metadata"; 
    _scopes[Scopes.DRIVE_METADATA_READONLY] = "https://www.googleapis.com/auth/drive.metadata.readonly"; 
    _scopes[Scopes.DRIVE_PHOTOS_READONLY] = "https://www.googleapis.com/auth/drive.photos.readonly"; 
    _scopes[Scopes.DRIVE_READONLY] = "https://www.googleapis.com/auth/drive.readonly"; 
    _scopes[Scopes.DRIVE_SCRIPTS] = "https://www.googleapis.com/auth/drive.scripts"; 
    return _scopes;
  }

  private this() {}
}
